services:
  localstack:
    image: localstack/localstack:2.3
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,dynamodb
      - AWS_DEFAULT_REGION=ap-southeast-2
      - DEBUG=0
    volumes:
      - "./.localstack:/var/lib/localstack"
